### ISSUE TITLE
CSV Scrobbler - Unusual characters

### ISSUE THREAD

**Issue by eodgh** [coczero/Last.fm-Scrubbler-WPF#49]
(I'm using version 1.18.0.0)

I'm using the CSV scrobbler and it's working fine apart from one situation:
If there are "unusual" characters outside the standard alphabet in the artist name, album title, or track title, scrobbling is possible  and the status will be shown as "Successfully scrobbled selected tracks", however they won't appear on last.fm.

Some examples of characters not accepted are
- Special characters like $, ¡, ß, €,§
- Anything with a diacritic, found in languages such as spanish, french, german, icelandic etc: ú, á, à, ê, í, ç, ä, ö, ü, to name a few...

Some examples and the csv file:
![grafik](https://user-images.githubusercontent.com/40181547/41252464-83a17dac-6dbd-11e8-887f-8e49612ced35.png)

Die Ärzte;Runter mit den Spendierhosen, Unsichtbarer!;Manchmal Haben Frauen...;11.06.2018 08:29;Die Ärzte;252
Green Day;¡UNO!;Nuclear Family;10.06.2018 19:06;Green Day;183
Coralie Clément;Salle des pas perdus;Mes fenêtres donnent sur la cour;08.06.2018 13:54;Coralie Clément;222
Coralie Clément;Salle des pas perdus;Ces matins déte;08.06.2018 13:39;Coralie Clément;173 
Múm;Finally We Are No One;The Land Between Solar Systems;08.06.2018 13:11;Múm;718
Múm;Finally We Are No One;Finally We Are No One;08.06.2018 13:00;Múm;307
Róisín Murphy;Overpowered;You Know Me Better;08.06.2018 12:09;Róisín Murphy;257

**Comment by coczero** [comment]
Fixed by https://github.com/coczero/Last.fm-Scrubbler-WPF/commit/15e65b0b445cc723d9b91e250b540feaf15f0c18

**Comment by pormarcelle** [comment]
I'm using the version 1.20 and this problem isn't completely solved. I'm still having issues with character set UTF-8 when I parse the file.

**Comment by theedgeofoblivious** [comment]
I am using the 1.21 beta and imported many songs with "é" and "í" characters in particular, and they did not import correctly.
